### ISSUE TITLE
Build script fails because (/var/lib/dpkg/lock) can't be locked.

### ISSUE THREAD

**Issue by SteveParson** [arnemertz/Xubuntu1604_DevBox#3]
unattended-upgrade gets the dpkg lock before your script does, causing it not to execute at all. I would suggest using aptdcon instead of apt-get so that you can queue the packages.

http://manpages.ubuntu.com/manpages/xenial/man1/aptdcon.1.html

**Comment by SteveParson** [comment]
I've looked into this further. While your script would be better served using aptdcon, the actual problem is in the Xubuntu 16.04 image. It looks like it fails to continue running through the vagrant script when it detects a mismatch in the guest additions module. The failure appears to be caused by a dpkg lock. 

[default] GuestAdditions versions on your host (5.0.24) and guest (5.0.18) do not match.
mesg: ttyname failed: Inappropriate ioctl for device
rmmod: ERROR: Module vboxguest is in use by: vboxvideo
mesg: ttyname failed: Inappropriate ioctl for device
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
mesg: ttyname failed: Inappropriate ioctl for device
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
mesg: ttyname failed: Inappropriate ioctl for device
Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
==> default: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get update

Stdout from the command:

Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu xenial InRelease
Hit:3 http://de.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://de.archive.ubuntu.com/ubuntu xenial-backports InRelease

Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

**Comment by arnemertz** [comment]
Hi @stevep1983 thanks for looking into this. I have seen this failure once in a while and did investigate without finding a good solution.  I probably should fix the image or even set it up again from scratch, switch off unattended-upgrade or wait for it in the provisioning script.

A workaround for now can be to comment out the provisioning line in the vagrantfile for the first boot, to give unattended-upgrade the opportunity to do its duty. Then shut down the machine, uncomment the provisioning line and boot again with `vagrant up --provision`

**Comment by SteveParson** [comment]
Thanks, I had no idea I could do that. I was just deleting your bash script and then executing it once everything was in order. Thanks again!
